---
version: 2
workflows:
  version: 2
  test:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/rust:1.74
    steps:
      - checkout

      - run: cargo --version

      - run:
          name: Format
          command: cargo fmt --all -- --check

      - run:
          name: Clippy
          command: cargo clippy -- -D clippy::all -D clippy::nursery -D warnings

      - run:
          name: Check
          command: cargo check

      - run:
          name: test
          command: cargo test
