---
version: 2
workflows:
  version: 2

jobs:
  build:
    docker:
      - image: cimg/rust:1.74
    steps:
      - checkout

      - run: cargo --version

      - run:
          name: Format
          run: cargo fmt --all -- --check

      - run:
          name: Clippy
          run: cargo clippy -- -D clippy::all -D clippy::nursery -D warnings

      - run:
          name: Check
          run: cargo check

      - run:
          name: test
          run: cargo test
