use crate::cli::telemetry::Verbosity;
use anyhow::{Context, Result};
use std::fmt::Write as _;
use std::net::IpAddr;
use std::process::Command;

pub fn generate(vpn_peer: &str, leak: bool, local: bool, verbose: Verbosity) -> Result<String> {
    let vpn_peer_ip: IpAddr = vpn_peer
        .parse()
        .context("Invalid VPN peer IP address")?;

    if verbose.is_debug() {
        eprintln!("  VPN peer: {vpn_peer_ip}");
        eprintln!("  Leak mode: {leak}");
        eprintln!("  Local network: {local}");
    }

    let mut rules = String::new();

    // Header
    rules.push_str("# VPN Kill Switch Rules\n");
    rules.push_str("# Generated by killswitch\n");
    rules.push('\n');

    // Block all IPv6 traffic
    rules.push_str("# Block all IPv6 traffic\n");
    rules.push_str("block out quick inet6 all\n");
    rules.push('\n');

    // Allow traffic to VPN peer
    rules.push_str("# Allow traffic to VPN peer\n");
    writeln!(rules, "pass out quick to {vpn_peer_ip}")?;
    rules.push('\n');

    // Allow loopback
    rules.push_str("# Allow loopback\n");
    rules.push_str("pass out quick on lo0\n");
    rules.push('\n');

    // Allow local network if requested
    if local {
        let local_networks = get_local_networks(verbose)?;
        if !local_networks.is_empty() {
            rules.push_str("# Allow local network traffic\n");
            for network in &local_networks {
                writeln!(rules, "pass out quick to {network}")?;
            }
            rules.push('\n');
            
            if verbose.is_debug() {
                eprintln!("  Local networks: {}", local_networks.join(", "));
            }
        }
    }

    // Allow DHCP (UDP port 67-68)
    rules.push_str("# Allow DHCP\n");
    rules.push_str("pass out quick proto udp to any port 67:68\n");
    rules.push('\n');

    // Allow ICMP and DNS if leak is enabled
    if leak {
        rules.push_str("# Allow ICMP (ping)\n");
        rules.push_str("pass out quick proto icmp all\n");
        rules.push('\n');

        rules.push_str("# Allow DNS\n");
        rules.push_str("pass out quick proto {tcp udp} to any port 53\n");
        rules.push('\n');
    }

    // Block everything else
    rules.push_str("# Block all other traffic\n");
    rules.push_str("block out all\n");

    Ok(rules)
}

fn get_local_networks(verbose: Verbosity) -> Result<Vec<String>> {
    let output = Command::new("ifconfig")
        .output()
        .context("Failed to execute ifconfig")?;

    if !output.status.success() {
        return Ok(Vec::new());
    }

    let stdout = String::from_utf8_lossy(&output.stdout);
    let mut networks = Vec::new();

    for line in stdout.lines() {
        // Look for inet lines with broadcast (indicating local network)
        if line.contains("inet")
            && line.contains("netmask")
            && line.contains("broadcast")
            && let Some(network) = extract_network(line)
        {
            if verbose.is_debug() {
                eprintln!("  Found local network: {network}");
            }
            networks.push(network);
        }
    }

    Ok(networks)
}

fn extract_network(line: &str) -> Option<String> {
    let parts: Vec<&str> = line.split_whitespace().collect();

    let inet_pos = parts.iter().position(|&s| s == "inet")?;
    let ip = parts.get(inet_pos + 1)?;

    let netmask_pos = parts.iter().position(|&s| s == "netmask")?;
    let netmask_hex = parts.get(netmask_pos + 1)?;

    // Convert hex netmask to CIDR
    let cidr = hex_to_cidr(netmask_hex)?;

    Some(format!("{ip}/{cidr}"))
}

fn hex_to_cidr(hex: &str) -> Option<u8> {
    let hex = hex.strip_prefix("0x")?;
    let value = u32::from_str_radix(hex, 16).ok()?;
    u8::try_from(value.count_ones()).ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[allow(clippy::unwrap_used)]
    #[test]
    fn test_generate_basic() {
        use crate::cli::telemetry::Verbosity;
        let rules = generate("10.8.0.1", false, false, Verbosity::Normal).unwrap();
        assert!(rules.contains("pass out quick to 10.8.0.1"));
        assert!(rules.contains("block out quick inet6 all"));
        assert!(rules.contains("block out all"));
    }

    #[allow(clippy::unwrap_used)]
    #[test]
    fn test_generate_with_leak() {
        use crate::cli::telemetry::Verbosity;
        let rules = generate("10.8.0.1", true, false, Verbosity::Normal).unwrap();
        assert!(rules.contains("pass out quick proto icmp all"));
        assert!(rules.contains("pass out quick proto {tcp udp} to any port 53"));
    }

    #[test]
    fn test_hex_to_cidr() {
        assert_eq!(hex_to_cidr("0xffffff00"), Some(24));
        assert_eq!(hex_to_cidr("0xffff0000"), Some(16));
        assert_eq!(hex_to_cidr("0xffffffff"), Some(32));
    }

    #[test]
    fn test_extract_network() {
        let line = "\tinet 192.168.1.100 netmask 0xffffff00 broadcast 192.168.1.255";
        assert_eq!(
            extract_network(line),
            Some("192.168.1.100/24".to_string())
        );
    }
}
